sudo: false
language: java
cache:
  directories:
  - "$HOME/.cache"
deploy:
  provider: script
  script: cp .travis.settings.xml $HOME/.m2/settings.xml && mvn deploy -Psign-source-javadoc
  skip_cleanup: true
  on:
    tags: true
notifications:
  email:
    recipients:
    - joseph.a.aruja@gmail.com
    on_success: change
    on_failure: always
env:
  global:
    secure: GGJnXHcL++gLVwOFLXldhrXehTciQXfek2XbdpYnBuRetG3x/nBDOt2rEn6wXZTJME4zCc9Qh56yzJTWdhzgU5ZpE/jwdDTc17s4SJDt519C5nIKq5mk7zUpj6GxIQh0cVgBok1Ai404fNPFVlvif+XC0LTiuJeR93b5LYcxi22T5puuaIGCi90M2h2gqPyahnStZmFVfx3bOe6kF4nZdQFG+j5nghDMNOWDxL2WlGMlVpiQinCxCiuMMzGNvFa4jjY+m92D00Qb750MKru5Tll5bjbrvqKIDMOZLnEeP+MhpfMYoYeTSH8sy+zo6kWt0r8BVYChjBjAzddV7E+xRyutdOJP+zlvvebkPKxjn3jfIZCHZxE1wqT6IGWz2j8Kec4PuioVsz4QRKLzTyNDVXgsm0VbW30otOEj3Ej6jsQ99Hk6znBJNYoFlCldrI5tbl/H9SDGtRvHfxPDc8S7/zUkB4Fhced3DKT37tAhvJ7AGJcQ9qdF3eJ7WMSK7YklLxp0Gpda7sg9MPoM7iYsI8ZzVkBQ9IXvTlVNZeLOG0Vv6K4EkCkDfRxZ59RAPBFRCtgs/Wc1E/o5ZZntERowY1ISzU+CUbzdXtRQ4urxUKNMcdE47uC4bLnBMlWMh0ZAp8kku3Mp3YQNMLghv5xZi0tW0MtGgvoJcRsJjButkh8=
